export interface instituteInfo {
    institute_id?: any;
    function_type?: any;
    username?: any;
    password?: any;
    onLoad?: any;
    school?: any;
    standard_id?: any;
    batch_id?: any;
    is_active?: any;
    subject_id?: any;
    course_id?: any;
    name?: any;
    phone?: any;
    email?: any;
    enquiry_no?: any;
    priority?: any;
    filtered_statuses?: any;
    status?: any;
    follow_type?: any;
    followUpDate?: any;
    enquiry_date?: any;
    assigned_to?: any;
    is_recent?: any;
    filtered_slots?: any;
    isDashbord?: any;
    enquireDateFrom?: any;
    enquireDateTo?: any;
    updateDate?: any;
    updateDateFrom?: any;
    updateDateTo?: any;
    is_load?: any;
    mobile?: any;
    language_inst_status?: any;
    slot_id?: any;
    master_course_name?: any;
    start_index ?: any;
    batch_size ?: any;
    closedReason?: any;
    enqCustomLi?: any;
}